version: "3.8"

services:
  ghost:
    image: ghost:5-alpine
    container_name: ghost
    restart: always
    ports:
      - "2368:2368"
    volumes:
      - ./ghost-content:/var/lib/ghost/content
    environment:
      url: http://localhost
      database__client: sqlite3
      database__connection__filename: /var/lib/ghost/content/data/ghost.db
