name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: SSH Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_DEPLOY_KEY_B64 }}" | base64 -d > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H 18.195.246.57 >> ~/.ssh/known_hosts

      - name: SSH into EC2 and deploy
        run: |
          ssh -i ~/.ssh/id_ed25519 ubuntu@18.195.246.57 << 'EOF'
            cd ~/drunken-banana
            git pull
            cd setup
            ./setup.sh
          EOF
